### ISSUE TITLE
Steal Neal's Urn doesn't get crossed out on Pip-Boy 

### ISSUE THREAD

**Issue by PxHC** [rotators/Fo1in2#118]
If you stole the urn before being told so and in the dialogue option says you already did when Vinnie asks, the quest doesn't mark as completed.

**Comment by Lexx2k** [comment]
I investigated this now. The quest will not be shown as completed until you return the urn to Neal. It's like that by design.

However, I've added a check to Neal's script instead -- if the urn quest is active and Neal dies, it will be set as completed.  https://github.com/rotators/Fo1in2/commit/aedba7ae8c83cdc7dc83f57f2d0cad1b6e4ca9ed

**Comment by HappyJarek** [comment]
> I investigated this now. The quest will not be shown as completed until you return the urn to Neal. It's like that by design.
> 
> However, I've added a check to Neal's script instead -- if the urn quest is active and Neal dies, it will be set as completed. [aedba7a](https://github.com/rotators/Fo1in2/commit/aedba7ae8c83cdc7dc83f57f2d0cad1b6e4ca9ed)

I've faced the same in my game, thank you for explanation.
