### ISSUE TITLE
Can't install on wine

### ISSUE THREAD

**Issue by burner1024** [rotators/Fo1in2#12]
Trying v0.1372 on wine, undat won't find some file

![Captura de pantalla de 2019-12-31 20-13-27](https://user-images.githubusercontent.com/1279852/71622704-52488180-2c0a-11ea-9f5c-44199ca67b52.png)

**Comment by Lexx2k** [comment]
Version 1.06 is the latest on repo, maybe that changes something?

Interestingly the file is in the wrong folder based on that error message. It should *not* be in the Fallout 1 folder. It's exactly where the undat.exe is.

**Comment by ghost2238** [comment]
Interesting. Hard to know what happened since there is no logging in the application at the moment. 

What happens if you put undat_files.txt in "c:\games\fallout\"?
Where does the exe reside?

I'll might add some logging on not found files and other errors for next version. I haven't used wine seriously for years so I don't know if there's any profile changes/recommendations to be made that will make it work better?

`var undatFilesPath = Directory.GetCurrentDirectory() + "\\undat_files.txt"` Is the code that finds the path to the file, nothing strange.

**Comment by burner1024** [comment]
```bash
$ ls fallout2/Fallout1in2/undat*
fallout2/Fallout1in2/undat.exe  fallout2/Fallout1in2/undat_files.txt
```
After copying to F1 dir, installation works.
So not a major problem, but strange.

Also, unrelated, but for some reason main menu art is not stretched enough, there are black bars on top/bottom. This is on 1280x800 res. In-game there's no such issue.
![scr00000](https://user-images.githubusercontent.com/1279852/71632547-9e62e880-2c41-11ea-94ca-512abd761bde.jpg)

**Comment by Lexx2k** [comment]
That's because I resized the main menu background to 720px height - the resolution I'm using (widescreen tho). The black bars at the top and bottom are due to MAIN_MENU_SIZE=0 in f2_res.ini - don't scale the menu.

I've set this as default, because I hate how the engine is scaling graphics (produces horrible pixel - originally it had a resolution of 1280x960px and I found it very noticable).

**Comment by burner1024** [comment]
> That's because I resized the main menu background to 720px height - the resolution I'm using (widescreen tho). The black bars at the top and bottom are due to MAIN_MENU_SIZE=0 in f2_res.ini - don't scale the menu.
> 
> I've set this as default, because I hate how the engine is scaling graphics (produces horrible pixel - originally it had a resolution of 1280x960px and I found it very noticable).
> You can still find the original HR_MAINMENU in the /art/intrface/ folder.
> 
> I'm considering this "experimental" right now, because I'm not sure if I will keep it that way... Generally I want it to be as close to the original Fo1 menu as possible, but there are certain limitations...

I see.

More on topic, maybe just include a simple bash script alternative for Linux/Mac OS users? Undat.exe requires dotnet to run.

**Comment by ghost2238** [comment]
Strange, did you run the file while in "c:\games\fallout"? Because the code retrieves the current working directory, which usually means the current directory of the shell. Should probably use the image path (exe) instead.

If someone wants to provide a Linux/Mac OS version I see no problem with including it, I don't use those platforms at the moment. A simple bash script doesn't work without some code that can handle Fallout 1 DAT files which contain files compressed with a custom LZSS compression invented by Interplay. There's a ton of those files. Fallout 2 DATs can be handled much like ZIP files.

More technical info:
https://github.com/rotators/Fo1in2/blob/master/Tools/UndatUI/src/dat.cs
https://fodev.net/files/fo2/dat.html

**Comment by burner1024** [comment]
> Strange, did you run the file while in "c:\games\fallout"? Because the code retrieves the current working directory, which usually means the current directory of the shell. Should probably use the image path (exe) instead.

No, I didn't.

> If someone wants to provide a Linux/Mac OS version I see no problem with including it, I don't use those platforms at the moment. A simple bash script doesn't work without some code that can handle Fallout 1 DAT files which contain files compressed with a custom LZSS compression invented by Interplay. There's a ton of those files. Fallout 2 DATs can be handled much like ZIP files.

I use [Anchorite's](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/tree/master/extra/bin) dat2 usually, works fine for me.

**Comment by ghost2238** [comment]
> No, I didn't.

Ok, thanks! Will investigate the issue further.

> I use [Anchorite's](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/tree/master/extra/bin) dat2 usually, works fine for me.

Alright, undat only unpacks the specified files in the txt file. With dat2 I guess you'd have to unpack everything to a temp dir and then copy the needed files. If someone wants to write such a script, I see no issue with including it in the release.

**Comment by burner1024** [comment]
Dat2 also supports reading a list from a file:
`dat2 x -d test4 ../../fallout/MASTER.DAT @undat_files.txt`. Is that enough, or you prefer an actual script?

**Comment by ghost2238** [comment]
I prefer a script, but in worst case we can include some instructions to run the above with Anchorite's dat2. Most linux users are probably able to do that without a script.

**Comment by ghost2238** [comment]
Might be fixed with 3fa28cb8442acf0a92937f79abd639951702cd4c.

@burner1024 could you try with the latest version (https://github.com/rotators/Fo1in2/blob/master/Tools/UndatUI/undat.exe)?

**Comment by burner1024** [comment]
Yes, that works too.

**Comment by ghost2238** [comment]
Cool, thanks for confirming!

**Comment by burner1024** [comment]
Windows crlf broken the script:
```
./undat.sh: línea 2: $'\r': orden no encontrada
: nombre de opción no válidopefail
```

**Comment by ghost2238** [comment]
Isn't this something that can be configured with git locally? dos2unix should work in this case. Mac uses only cr for new line also so it will always be broken on at least one other major platform.

**Comment by burner1024** [comment]
Git maybe, but I mean the release package.

According to my information, [Mac OS is fine](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/27) using Linux lf, I got [the same script](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/release/rpu-install.bat) covering both.

**Comment by ghost2238** [comment]
I see. 

@wipe2238 - Would `dos2unix "$MOD_DIR/undat.sh"` in the `Copy UndatCLI` part of https://github.com/rotators/Fo1in2/blob/master/.github/workflows/package.yml work?

**Comment by wipe2238** [comment]
Has to be git thing; my local copy on *nix shows LF, windows one shows CRLF. And as package is created under windows image... heh. `dos2unix` saved a day once again.
