### ISSUE TITLE
Fill_W not uncovering all zones till the map edge

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#16]
Minor but somewhat annoying issue:

Unlike in Fo1, the `Fill_W` flag in Fo2 (set in worldmap.txt) doesn't uncover zones up to the very end of the left screen side.

![Ocean](https://i.imgur.com/I4rFjup.png)

This is some odd behavior, as it doesn't look consistent... Here is the Fo1 worldmap with the zones and how they will uncover right now: https://i.imgur.com/vjz4BJi.png

As you can see, everything works fine until we are reaching the zone row at the height of the cathedral location. There suddenly Fill_W doesn't reach to the map border anymore. 
That gets worse once more in the very last row.

Maybe there is some engine limitation going on here?
Anything we can do about this?

**Comment by CyberMayck** [comment]
From looking at it and walking around the map it is obvious that the map being uncovered is limited by Tile borders (since tiles are 7x6 zones and its 7 or 14 zones missing from the map edge).

Also at the very bottom line of the map there are two zones you can step on to with that reveal flag. And since each is on different tile and one reveals 7 zones to the left and other reveals 13 it easily demonstrates how it actually works:

**When the reveal zone is stepped on, it reveals rest of the zones to the left in the current worldmap tile and also all zones in one worldmap tile further to the left.**

So it would somehow need to check, if there are additional Tiles beyond that and reveal those. Since didn't have ocean that would be wider than two worldmap tiles, it does not happen there. This probably requires some deeper knowledge to fix...

**Comment by Lexx2k** [comment]
Another note to this: 
I tried to workaround this with giving all zones to the left the `Fill_W` flag, but sadly the game doesn't recognize them. So it seems the player must step on these zones- just revealing them does not trigger the `Fill_W` flag-effect.

**Comment by Lexx2k** [comment]
We have added a script solution for this. https://github.com/rotators/Fo1in2/commit/df4100a5914b8eef6ee174830866f9cd9d6be8da

Problem is that it works with a noticable delay, so ultimately fixing this "in engine" would be preferable. It's not super important right now, though.

**Comment by ghost2238** [comment]
I've implemented this as a bytepatch in script, see https://github.com/rotators/Fo1in2/commit/87750f803e3038729908bbf6b73c55611d40ce13, should be possible to remove the script code in gl_worldmap.ssl now that we have a proper solution.
