### ISSUE TITLE
Check if full optimization explodes scripts

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#2]
Just a reminder for future selves to check if scripts compiled with `-O2` aka `Full optimization` breaks anything. ToDo on next full run, whenever it gonna be.
```
22:31 < lexx> i'm pretty sure there is a reason why i have not set it to full
```

**Comment by FakelsHub** [comment]
https://github.com/FakelsHub/int-sslc/issues/1

**Comment by Lexx2k** [comment]
Found lots of issues related to that and reverted the scripts because of that.

**Comment by wipe2238** [comment]
Allrighty then. I'll keep `-O2` in Actions anyway (so we'll still see fancy warnings from optimizer there), and use `--optimization=1` from 3700cba when/if we start .int autocommits.

**Comment by FakelsHub** [comment]
> 
> 
> Reverted the scripts, because I found lots of issues related to that now (game crashes with some scripts, etc).

any examples of incorrect optimization?

**Comment by Lexx2k** [comment]
I don't know which script exactly caused it, but some of the encounter crashed my game. After I recompiled the encounter scripts, the crashes weren't happening anymore.
I suspect it was [GENGRDA](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/Mapper/source/scripts/encounter/GENGRDA.ssl), but can't say for sure right now (especially because the script looks totally fine to me).

**Comment by FakelsHub** [comment]
Obviously the problem is not in these scripts, they are absolutely identical for O1 and O2 optimizations.

**Comment by burner1024** [comment]
When I was revising UP/RP for full optimization, I just mass compiled/decompiled both variants and ran a diff.
Most, or all problems were related to NodeXXX passed in variables, which was fixed by using [stringify operator](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/commit/ad7e26e9283cca06a4360874e4c34ded70bf28be).
