### ISSUE TITLE
Ghost of Tandi

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#23]
When entering Raiders for first time, fake Tandi shows up near entrance to building. Disappears if you gently touch her with cursor.

https://i.imgur.com/n3vPlZy.png
https://i.imgur.com/ivn6NEU.png

**Comment by Lexx2k** [comment]
Can you reproduce this every time?

It's just a graphic glitch, likely because of the hardware you are using. :>

She isn't a new critter that gets created. Once Tandi has been kidnapped, she pretty much acts as an invisible companion to the player. After entering Raiders, she gets teleported into the cell - which is what is causing your issue. I can check out some other stuff, but I doubt it's fixable.

**Comment by wipe2238** [comment]
Three times in a row is enough. Blaming my hardware isn't funny since a month at least, stop living a past :p It didn't happen last time i was rescuing Tandi, or any time before for that matter (including xp-dev times).

**Comment by ghost2238** [comment]
> 
> 
> Can you reproduce this every time?
> 
> It's just a graphic glitch, likely because of the hardware you are using. :>
> 
> She isn't a new critter that gets created. Once Tandi has been kidnapped, she pretty much acts as an invisible companion to the player. After entering Raiders, she gets teleported into the cell - which is what is causing your issue. I can check out some other stuff, but I doubt it's fixable.

The fact that she is visible in the first position can't be just a graphical glitch, the overdraw stuff with mouse cursor after she has teleported is likely because a full refresh of the buffer is not done, so the graphic is still in the buffer yet the NPC has been moved.

Haven't seen this bug during testing myself, but might this be yet another one of those subtle differences between FO1/FO2, where they did some hardcoding for this specific map, making Tandi not spawn in that initial position?

**Comment by Lexx2k** [comment]
I'm pretty sure this is because Tandi is a regular party member who is made visible as soon as you enter the map, and at the same time gets moved into the prison cell. It happens at the same time, thus she still appears on her hex where she spawned:

```
         if (tandi_is_kidnapped and (global_var(GVAR_TANDI_LOCATION_TRACKER) == 1)) then begin
            set_self_abandon_party;
            if not(is_loading_game) then set_self_visible;
            critter_attempt_placement(self_obj, 17905, 0);
            set_global_var(GVAR_TANDI_LOCATION_TRACKER, 2);
         end
``` 
I've switched "be visible" with the move command, maybe this helps. Can't test this myself, so I dunno yet.

**Comment by wipe2238** [comment]
Quick cheat-test says it works, but gonna check it again on regular run later.
