### ISSUE TITLE
How to get F2 mechanics back

### ISSUE THREAD

**Issue by burner1024** [rotators/Fo1in2#37]
In particular, skill cost and max. I think F2 way is better.

**Comment by Lexx2k** [comment]
Skill costs are defined in the /config/skills.ini file. If you delete it, you'll get Fo2 values back. Personally I advise against this, though, because it unbalances the game a lot. For example, you will start the game with a very high Outdoorsman skill, etc which doesn't fit into the Fo1 setting.

200% max skill is set in gl_fo1mechanics.ssl - I could probably add a toggle for that, but it doesn't feel worth it to me, because: barely anyone will make it to > 200% skills, and in Fo1 it is completely useless to put more than ~100% into any skill.

**Comment by burner1024** [comment]
Are starting values also different? Didn't notice that.
Thing is, I got to 150+ in guns even before taking out the raiders, which seems a little too easy.

**Comment by Lexx2k** [comment]
It's the way the skills are calculated that is very different in Fo1. 
For Small Guns, as example, the initial value is `35% + (1% * AG)` while in Fo2 it is `5% + (4% * AG)` - obviously this makes a huge difference. :>

**Comment by burner1024** [comment]
But I like suffering...
Actually, assuming 9-10 AG, with which I strongly suspect almost everyone starts out, it's pretty much the same.
Anyway, I take your point.

**Comment by Lexx2k** [comment]
I never use 9-10 AG. :D My characters have never more than max. 8 APs, usually I just roll with 7 APs even.

**Comment by burner1024** [comment]
> I never use 9-10 AG. :D My characters have never more than max. 8 APs, usually I just roll with 7 APs even.

Guess you like suffering even more than I :).



> What would make the game harder is changing the required skill points per +% of skill increase. And this can be adjusted in the skills.ini file.

Well, I looked at it, but format isn't immediately, maybe add an example or something?

**Comment by wipe2238** [comment]
>Well, I looked at it, but format isn't immediately obvious, maybe add an example or something?

https://github.com/phobos2077/sfall/blob/master/artifacts/config_files/Skills.ini

I feel sfall should be handled differently, it's not even first time we get question about it from people who would rather use FO2 formula.

**Comment by burner1024** [comment]
> https://github.com/phobos2077/sfall/blob/master/artifacts/config_files/Skills.ini

Ah, this is native sfall thing, I thought it was something EtTu-specific. In that case, I'd like to suggest to at least keep the explanation inside the file.

**Comment by Lexx2k** [comment]
Huh, this file looks different than the one we use. Looks like `BasedOnPoints=0` is new. When I did the skill changes, it was still based around `SkillCost0=300` which means with a max of 300%, 1 skill point will set 1%.

**Comment by Anarcho-Bolshevik** [comment]
What about the new perks that _Fallout 2_ added? Would those be worth including? (Excluding the implants and other special perks, the new ones are Adrenaline Rush, Cautious Nature, Comprehension, Demolition Expert, Gain, Gambler, Harmless, Here and Now, HtH Evade, Kama Sutra Master, Karma Beacon, Light Step, Living Anatomy, Magnetic Personality, Negotiator, Pack Rat, Pyromaniac, Quick Recovery, Salesman, Stonewall, Thief, and Weapon Handling.)

**Comment by Lexx2k** [comment]
They already are in the game.

**Comment by Anarcho-Bolshevik** [comment]
Damn, I should have checked more thoroughly before saying anything boneheaded. Umm… is it too late to specify these additions in README.md?

**Comment by FyiurAmron** [comment]
> What about the new perks that _Fallout 2_ added? Would those be worth including? (...) the new ones are (...) Gain

> Those are already in the game.

maybe I'm dumb, but it seems some of them (`Gain *` to be specific) were removed anyway

https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/config/Perks.ini#L167

**Comment by Lexx2k** [comment]
Yes, because they are stupid in Fo1. The game is already easy enough, and SPECIAL doesn't have as much weight as in Fo2.

**Comment by FyiurAmron** [comment]
>Yes, because they are stupid in Fo1. The game is already easy enough, and SPECIAL doesn't have as much weight as in Fo2.

@Lexx2k not that I disagree with this particular statement (frankly, both FO1 & FO2 are easy as hell regardless of settings), but it still means that you were not right by saying "Those are already in the game.", since they ain't, at least not all of the ones mentioned. I guess that someone who doesn't see them in-game although someone stated that "[they] are already in the game" will find the situation confusing. That was my only point here.

**Comment by Lexx2k** [comment]
You are right, I am wrong. Bit nitpicky, but whatever. Now you know what file to edit to get them back.
