### ISSUE TITLE
Empty random encounters

### ISSUE THREAD

**Issue by Lrflx** [rotators/Fo1in2#76]
Sometimes after my character is being stopped by encounter he then just spawns in empty generic desert location, without any text or any interactive objects at all around, no messages about water searching or anything, and there's nothing for me to do there but just move on. It's not anything really gamebreaking in any way, just kinda strange behaviour. Using the latest release without anything added on top.

**Comment by Lexx2k** [comment]
Needs more information. Where did this happen, what daytime was it, etc.

**Comment by Lrflx** [comment]
It happened several times between Shady Sands and Junktown, I think both during day and nighttime. The very beginning, no perks, I did tweak sfall a bit and disabled stuff from 2nd game. Also made a save when I got it last time.
[EncSav.zip](https://github.com/rotators/Fo1in2/files/5545478/EncSav.zip)

**Comment by Lexx2k** [comment]
What exactly was disabled?

**Comment by Lrflx** [comment]
Caves and encounters with monsters from FO2.

**Comment by Lrflx** [comment]
Actually scratch that, retested it with default f2_res and ddraw and new character and got it pretty fast in area near Junktown.

**Comment by Lexx2k** [comment]
Potentially fixed it now https://github.com/rotators/Fo1in2/commit/a764e41b4036c0cd18f4700184ba2fb18f8db9bc

After adding a billion new debug messages and tracking every single step of the encounter creation, I nailed the issue down to `critter_attempt_placement(Item, spawn_hex, scenery_elevation);` in the scenery creation procedure. No idea why - the objects always seem to be valid.
A workaround is to simply spawn the objects directly on the wanted hex, and not move them there. However, the problem is that scenery objects can now potentially spawn into each other - I'll keep it like that for now, though, because I don't really know what else to do instead.
